### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by vinhbui1** [google-developer-training/basic-android-kotlin-compose-training-unscramble#112]
fun resetGame() {
   usedWords.clear()
   _uiState.value = GameUiState(currentScrambledWord = pickRandomWordAndShuffle())
}

error in    usedWords.clear()
because it null 

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
                                                                                                    	at com.example.unscramble.ui.GameViewModel.pickRandomWordAndShuffle(GameViewModel.kt:24)
                                                                                                    	at com.example.unscramble.ui.GameViewModel.resetGame(GameViewModel.kt:39)
                                                                                                    	at com.example.unscramble.ui.GameViewModel.<init>(GameViewModel.kt:11)
                                                                                                    	... 101 more

**Comment by rosie-i** [comment]
In case anyone else comes across this, I had a similar NullPointerException and it was solved by moving the property initializers above the init block. So essentially, ensure you must declare usedWords and _uiState before the init block.

The codelab didn't explain that you need to do this and I come from a JavaScript background where you can declare a getter or a method further down in a class and then still call it in the constructor (because default JS behaviour is to hoist all declarations from the class first). 

Here's a helpful article I found about execution order of initializers in Kotlin:
https://medium.com/keepsafe-engineering/an-in-depth-look-at-kotlins-initializers-a0420fcbf546
