### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by bsudhanva** [google-developer-training/basic-android-kotlin-compose-training-unscramble#212]
```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.Set.clear()' on a null object reference
                                                                                                    	at com.example.unscramble.ui.GameViewModel.resetGame(GameViewModel.kt:41)
                                                                                                    	at com.example.unscramble.ui.GameViewModel.<init>(GameViewModel.kt:14)
```

The app crashes at start, and stack trace points at init method in that resets used words .
Specifically at [[Link to tutorial page](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#4
)
Got the error while i was at step 6 of  [Link to tutorial page](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#5)

As a mitigation I had added if else for null checking, even then it produces this error 
Null safety code
```
fun resetGame(){
if (usedWords != null)
	{usedWords.clear()
		_uiState.value = GameUiState(currentScrambledWord = pickRandomWordAndShuffle())
    }

		else _uiState.value = GameUiState(currentScrambledWord = pickRandomWordAndShuffle())
}
```
Log cat says-
```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.contains(java.lang.Object)' on a null object reference
                                                                                                    	at com.example.unscramble.ui.GameViewModel.pickRandomWordAndShuffle(GameViewModel.kt:52)
                                                                                                    	at com.example.unscramble.ui.GameViewModel.resetGame(GameViewModel.kt:43)
                                                                                                    	at com.example.unscramble.ui.GameViewModel.<init>(GameViewModel.kt:14)
```

And for sake of testing if i remove else block and use `Unit`, app launches without any error , but then there is no scrambled word displayed .

code - 
```
if (usedWords != null)
	{usedWords.clear()
		_uiState.value = GameUiState(currentScrambledWord = pickRandomWordAndShuffle())}

		else Unit
```

**Comment by thomasem** [comment]
Seems like this is related to whether the `init` block is before or after `usedWords` is created, which should be initialized with an empty set like

```
    private var usedWords: MutableSet<String> = mutableSetOf()
```

If the `init` block that calls `reset()` is included before this line, it will throw a `NullPointerException`
